<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-11 11:11
=======
# Generated by Django 5.2.3 on 2025-06-27 15:58
>>>>>>> 7f777d47fb42514aeab1dc28db82375ee44209e0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
=======
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
>>>>>>> 7f777d47fb42514aeab1dc28db82375ee44209e0
            ],
        ),
    ]
